[package]
name = "lightning-tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
native-tls = "0.2"
url = "2.4"
base64 = "0.21"
rand = "0.8"
serde_json = "1.0.140"
colored = "3.0.0"
serde = { version = "1.0.219", features = ["derive"] }